name = "Cranberry"
grammar = "cranberry"
path_suffixes = ["cb"]
line_comments = ["# "]
tab_size = 4
hard_tabs = true
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
  { start = "`", end = "`", close = true, newline = false },
]
