id = "cranberry-extension"
name = "Cranberry"
version = "0.0.1"
schema_version = 1
authors = ["creepersaur"]
description = "Cranberry programming language support for Zed."
repository = "https://github.com/creepersaur/ZedCranberry"

[grammars.cranberry]
repository = "https://github.com/creepersaur/tree-sitter-cranberry"
commit = "ba9827e59befab2be0a02bc483ad363731a539c7"
