id = "cranberry-extension"
name = "Cranberry"
version = "0.0.1"
schema_version = 1
authors = ["creepersaur"]
description = "Cranberry programming language support for Zed."
repository = "https://github.com/creepersaur/ZedCranberry"

[grammars.cranberry]
repository = "https://github.com/creepersaur/tree-sitter-cranberry"
commit = "d85bded77c6091a989954f01decb742ca8304a37"

[language_servers.cranberry-lsp]
name = "cranberry-lsp"
languages = ["Cranberry"]
